var qns = [
	"Count total no. of figures in the below image.",
	"Count total no. of figures in the below image.",
	"Which horse is different?",
	"Which horse is different?",
	"Which one is different?",
	"Which one is different?",
	"Which colors are the same ?",
	"Which colors are the same ?",
	"How many squares are there ?",
	"How many squares are there ?",
	"Which one is different",
	"Which one is different",
	"How many triangles are present in the below figure ?",
	"How many triangles are present in the below figure ?",
	"Which of the below figures is different?",
	"Which of the below figures is different?",
	"Count the number of differences in the below images.",
	"Count the number of differences in the below images.",
	"How many rectangles are there in the figure?",
	"How many rectangles are there in the figure?",
	"Which one is different",
	"Which one is different",
	"Which one is different",
	"Which one is different",
	"Which one is different",
	"Which one is different",
	"Count no. of difference for below two images",
	"Count no. of difference for below two images",
	"Count no. of difference for below two images",
	"Count no. of difference for below two images",
	"Count no. of difference for below two images",
	"Count no. of difference for below two images",
	"How many differences are there between the above two images?",
	"How many differences are there between the above two images?",
	"Choose a figure which is different from the rest.",
	"Choose a figure which is different from the rest.",
	"Choose a figure which is different from the rest.",
	"Choose a figure which is different from the rest.",
	"How many differences are there between the above two images?",
	"How many differences are there between the above two images?",
	"Choose the correct spelling",
	"Choose the correct spelling",
	"Select the word with correct spelling",
	"Select the word with correct spelling",
	"Which is the top view?",
	"Which is the top view?",
	"Can you find the the mistake?",
	"Can you find the the mistake?",
	"Select the image different from the rest",
	"Select the image different from the rest",
	"Find the missing number.",
	"Find the missing number.",
	"Which path takes you out of the maze?",
	"Which path takes you out of the maze?",
	"How many colors can you see?",
	"How many colors can you see?",
	"Which square looks different?",
	"Which square looks different?",
	"How many 9s can you see in the above picture?",
	"How many 9s can you see in the above picture?",
];
var ans = [
	"B",
	"B",
	"D",
	"D",
	"B",
	"B",
	"D",
	"D",
	"B",
	"B",
	"S",
	"S",
	"C",
	"C",
	"C",
	"C",
	"C",
	"C",
	"B",
	"B",
	"A",
	"A",
	"D",
	"D",
	"C",
	"C",
	"C",
	"C",
	"B",
	"B",
	"A",
	"A",
	"B",
	"B",
	"D",
	"D",
	"A",
	"A",
	"C",
	"C",
	"C",
	"C",
	"C",
	"C",
	"C",
	"C",
	"B",
	"B",
	"D",
	"D",
	"A",
	"A",
	"C",
	"C",
	"A",
	"A",
	"A",
	"A",
	"D",
	"D",
];
var imgs = [
	"1.png",
	"1.png",
	"2.png",
	"2.png",
	"3.png",
	"3.png",
	"4.png",
	"4.png",
	"5.png",
	"5.png",
	"6.png",
	"6.png",
	"7.png",
	"7.png",
	"8.png",
	"8.png",
	"9.png",
	"9.png",
	"10.png",
	"10.png",
	"11.png",
	"11.png",
	"12.png",
	"12.png",
	"13.png",
	"13.png",
	"14.png",
	"14.png",
	"15.png",
	"15.png",
	"16.png",
	"16.png",
	"image17.png",
	"image17.png",
	"image18.png",
	"image18.png",
	"image19.png",
	"image19.png",
	"image20.png",
	"image20.png",
	"image21.png",
	"image21.png",
	"image22.png",
	"image22.png",
	"image23.png",
	"image23.png",
	"image24.png",
	"image24.png",
	"image25.png",
	"image25.png",
	"image26.png",
	"image26.png",
	"image27.png",
	"image27.png",
	"image29.png",
	"image29.png",
	"image30.png",
	"image30.png",
	"image.png",
	"image.png",
];
var options = [
	["5", "7", "9", "8"],
	["5", "7", "9", "8"],
	["1", "2", "3", "All are same"],
	["1", "2", "3", "All are same"],
	["1", "2", "3", "All are same"],
	["1", "2", "3", "All are same"],
	["2 and 3", "1 and 2", "3 and 4", "None of the options"],
	["2 and 3", "1 and 2", "3 and 4", "None of the options"],
	["30", "35", "40", "45"],
	["30", "35", "40", "45"],
	["P", "Q", "R", "S"],
	["P", "Q", "R", "S"],
	["20", "24", "21", "23"],
	["20", "24", "21", "23"],
	["A", "B", "C", "D"],
	["A", "B", "C", "D"],
	["15", "5", "10", "20"],
	["15", "5", "10", "20"],
	["8", "9", "10", "7"],
	["8", "9", "10", "7"],
	["A", "B", "C", "D"],
	["A", "B", "C", "D"],
	["A", "B", "C", "D"],
	["A", "B", "C", "D"],
	["A", "B", "C", "D"],
	["A", "B", "C", "D"],
	["10", "11", "12", "14"],
	["10", "11", "12", "14"],
	["3", "5", "7", "9"],
	["3", "5", "7", "9"],
	["10", "11", "9", "5"],
	["10", "11", "9", "5"],
	["7", "9", "6", "13"],
	["7", "9", "6", "13"],
	["1", "3", "4", "5"],
	["1", "3", "4", "5"],
	["1", "2", "3", "5"],
	["1", "2", "3", "5"],
	["13", "10", "9", "11"],
	["13", "10", "9", "11"],
	["C", "A", "D", "B"],
	["C", "A", "D", "B"],
	["D", "C", "A", "B"],
	["D", "C", "A", "B"],
	["C", "D", "B", "A"],
	["C", "D", "B", "A"],
	["2,4,8", "5,9", "1,3,5,7", "3,7"],
	["2,4,8", "5,9", "1,3,5,7", "3,7"],
	["A", "B", "C", "None"],
	["A", "B", "C", "None"],
	["22", "13", "31", "24"],
	["22", "13", "31", "24"],
	["C", "A", "B", "None"],
	["C", "A", "B", "None"],
	["5", "7", "4", "6"],
	["5", "7", "4", "6"],
	["B", "D", "A", "C"],
	["B", "D", "A", "C"],
	["8", "7", "11", "9"],
	["8", "7", "11", "9"],
];
